import type { Metadata } from "next";

/** styles */
import { Inter } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "@/view/lib/styledComponents/registry";
import "@mantine/core/styles.css";
import {
  MantineColorSchemeScript,
  MantineContextProvider,
  MantineDefaultTheme,
} from "@/view/lib/mantine/registry";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <MantineColorSchemeScript />
      </head>
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <MantineContextProvider theme={MantineDefaultTheme}>
            {children}
          </MantineContextProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
